repos:
-   repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
    - id: black
      args: [--safe]
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
      args: ['--max-line-length=88', '--select=W291,W292,W293,F401']
      language_version: python3
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'
    hooks:
    -   id: mypy
        args: []
        additional_dependencies: [ types-PyYAML, pydantic ]
        exclude: docs
